converter
liubinski27/Currency-Converter pull request #2
Opened 2020-10-15 10:03 UTC by liubinski27

2020-10-16 17:40 UTC, kirill-malyhin commented on src/app/app.module.ts
> +    { path: '', component: CoursesComponent },
should be splitted to separate file

2020-10-16 17:40 UTC, kirill-malyhin commented on src/app/converter.service.ts
> +      this.currenciesList = response.map(item => ({
move processing into separate function in service

2020-10-16 17:40 UTC, kirill-malyhin commented on src/app/converter/converter.component.html
> +    <app-date (onChanged)="getCurrencies($event)"></app-date>
(onChanged) -> (onChange)

2020-10-16 17:40 UTC, kirill-malyhin commented on src/app/converter/converter.component.scss
> +    .loading {
should be a common class as it is declared also in other place

2020-10-16 17:40 UTC, kirill-malyhin commented on src/app/converter/converter.component.ts
> +      this.savedCurrencyValue = 0;
as we discussed, we don't store value

2020-10-16 17:40 UTC, kirill-malyhin commented on src/app/converter/converter.component.ts
> +      this.savedCurrencyIndex = 0;
we store only selected currencies

2020-10-16 17:40 UTC, kirill-malyhin commented on src/app/converter/converter.component.ts
> +      const foundCurrencyAbbreviation = this.selectedCurrenciesAbbreviations.find(el => el === item.abbreviation);
foundCurrencyAbbreviation  -> currencyAbbreviation

2020-10-16 17:40 UTC, kirill-malyhin commented on src/app/header/header.component.html
> +                            <li (click)="changeLang('ru')">Русский</li>
'ru', 'en' move to enum

2020-10-16 17:40 UTC, kirill-malyhin commented on src/app/header/header.component.html
> +                            <img src="../../assets/styles/pictures/pngegg.png" alt="language">
rename pngegg to something not shitty

2020-10-16 17:40 UTC, kirill-malyhin commented on src/index.html
> +  <title>Currency-Converter</title>
Currency Converter

2020-10-18 22:05 UTC, liubinski27 commented on src/app/converter/converter.component.ts
> +      this.savedCurrencyValue = 0;
this is the function for deleting inputs, these variables are not stored

2020-10-18 22:09 UTC, liubinski27 commented on src/app/converter/converter.component.ts
> +      this.savedCurrencyIndex = 0;
maybe the variables are named incorrectly, as we store only selected currencies

2020-10-19 07:16 UTC, kirill-malyhin requested changes

2020-10-19 07:16 UTC, kirill-malyhin commented on src/app/language.service.ts
> +    translateService.use('ru');
one more improvement, create function init and call it from app.component

2020-10-19 07:16 UTC, kirill-malyhin commented on src/app/converter.service.ts
> +    this.mapLoadedCurrencies(subject, url);
what kind of subject are your returning? you added unexpected async behavior, just write function, which will return processed object

2020-10-19 07:16 UTC, kirill-malyhin commented on src/app/converter/converter.component.ts
> +    '../../assets/styles/scss/common.scss'
wrong way of doing such thinks. common.scss should be added into styles.scss in that case

2020-10-19 07:16 UTC, kirill-malyhin commented on src/app/converter/converter.component.ts
> +          const SelectedCurrency = this.selectedCurrencies.find(item => item === foundCurrencyInCurrenciesList);
why first letter is upper?

2020-10-19 07:16 UTC, kirill-malyhin commented on src/app/header/header.component.html
> +                            <li (click)="changeLang(eLanguagesList.russian)">Русский</li>
value of enum should be UPPER CASE

2020-10-19 07:16 UTC, kirill-malyhin commented on src/app/header/header.component.ts
> +  russian = 'ru',
RUSSIAN: 'ru'

2020-10-19 07:16 UTC, kirill-malyhin commented on src/styles.scss
> +/* You can add global styles to this file, and also import other style files */
here you should add common.scss

2020-10-19 12:25 UTC, kirill-malyhin approved these changes

2020-10-19 12:25 UTC, merged